SELECT * FROM competitors
WHERE ticker_id='AAPL';

DROP TABLE competitors

CREATE TABLE competitors(
    competitor VARCHAR(10) NOT NULL,
	ticker_id VARCHAR(10) NOT NULL,
	FOREIGN KEY (ticker_id) references profiles (ticker_id)
);

INSERT INTO competitors(competitor, ticker_id)
VALUES
('Samsung', 'AAPL'),
('XIACF', 'AAPL'),
('LNVGY', 'AAPL'),
('DELL', 'AAPL'),
('ADSK', 'ADBE'),
('CRM', 'ADBE'),
('SAP', 'ADBE'),
('CREL', 'ADBE'),
('MSFT', 'AMZN'),
('GOOGLL', 'AMZN'),
('BABA', 'AMZN'),
('WMT', 'AMZN'),
('ABNB', 'BKNG'),
('TRIP', 'BKNG'),
('TRVG', 'BKNG'),
('EXPE', 'BKNG'),
('WMT', 'COST'),
('HD', 'COST'),
('TGT', 'COST'),
('BJ', 'COST'),
('MSFT', 'CRM'),
('ORCL', 'CRM'),
('SAP', 'CRM'),
('ADBE', 'CRM'),
('CMCSA', 'DIS'),
('NFLX', 'DIS'),
('AMZN', 'DIS'),
('AAPL', 'DIS'),
('GOOGL', 'FB'),
('TWTR', 'FB'),
('ByteDance', 'FB'),
('SNAP', 'FB'),
('AMZN', 'GOOGL'),
('FB', 'GOOGL'),
('MSFT', 'GOOGL'),
('BABA', 'GOOGL'),
('ACN', 'IBM'),
('HPQ', 'IBM'),
('XRX', 'IBM'),
('ORCL', 'IBM'),
('MRK', 'JNJ'),
('UL', 'JNJ'),
('PFE', 'JNJ'),
('PG', 'JNJ'),
('PEP', 'KO'),
('PG', 'KO'),
('UL', 'KO'),
('MNST', 'KO'),
('SBUX', 'MCD'),
('QSR', 'MCD'),
('KFC', 'MCD'),
('Subway', 'MCD'),
('AMZN', 'MSFT'),
('AAPL', 'MSFT'),
('GOOGL', 'MSFT'),
('SAP', 'MSFT'),
('DIS', 'NFLX'),
('AMZN', 'NFLX'),
('GOOGLL', 'NFLX'),
('CMCSA', 'NFLX'),
('ADDYY', 'NKE'),
('RBK', 'NKE'),
('PUM', 'NKE'),
('UA', 'NKE'),
('AMD', 'NVDA'),
('INTC', 'NVDA'),
('QCOM', 'NVDA'),
('AVGO', 'NVDA'),
('GOOGLL', 'PYPL'),
('Skrill', 'PYPL'),
('Wepay', 'PYPL'),
('PAYO', 'PYPL'),
('MCD', 'SBUX'),
('CMG', 'SBUX'),
('YUM', 'SBUX'),
('DPZ', 'SBUX'),
('TM', 'TSLA'),
('GM', 'TSLA'),
('HMC', 'TSLA'),
('F', 'TSLA'),
('BABA', 'WMT'),
('HD', 'WMT'),
('COST', 'WMT'),
('AMZN', 'WMT');